In [ ]:
import pandas as pd
import google.colab as drive
import numpy as np
import matplotlib as plt
from matplotlib import pyplot
import matplotlib.pyplot as plt
from matplotlib import rcParams
import seaborn as sns


#Hola mundo

In [ ]:
# Cargo el link del dataset
bd ='/content/drive/MyDrive/Colab Notebooks/Analisis_exploratorio_datos/dataset_fumadores.xlsx'
# Asigno los encabezado
headers = ["edad","sexo","imc","hijos","fumador", "region","costo"]
# Asigno la data y el encabezado
data = pd.read_excel(bd, names=headers)
# Leo las 5 primeras lineas del la data
data.head(5)

edad       sexo     imc  hijos fumador    region        costo
0    19   femenino  27.900      0      si  suroeste  16884.92400
1    18  masculino  33.770      1      no   sureste   1725.55230
2    28  masculino  33.000      3      no   sureste   4449.46200
3    33  masculino  22.705      0      no  noroeste  21984.47061
4    32  masculino  28.880      0      no  noroeste   3866.85520

In [ ]:
#print(data.dtypes)

In [ ]:
# Vemos la forma de la data
data.shape

(1338, 7)

In [ ]:
#Observamos los tipo de datos
#print(data.dtypes)

In [ ]:
#data.isna().sum()

In [ ]:
#verificamos los encabezado de la data
#data.columns

In [ ]:
data.dtypes

edad         int64
sexo        object
imc        float64
hijos        int64
fumador     object
region      object
costo      float64
dtype: object

### Remplazando valore perdidos

In [ ]:
# Reemplazar "?" por NaN, notengo valores perdidos
#data.replace("?", np.nan, inplace = True)
#data.head(5)

## Evaluando los datos

In [ ]:
#missing_data = data.isnull()
#missing_data.head(5)

Contar los valores perdidos de cada columna

In [ ]:
#for column in missing_data.columns.values.tolist():
 #   print(column)
 #   print (missing_data[column].value_counts())
 #   print("")    

Para contar los valores perdidos que hay en cada atributo.

El resumen de los valores perdidos para los atributos del dataset.
 (.isnull(), .notnull(), y .isna()).) despues .sum() 

In [ ]:
data.isna().sum()

edad       0
sexo       0
imc        0
hijos      0
fumador    0
region     0
costo      0
dtype: int64

##Corregir formato de datos

In [ ]:
#Cambiamos los formatos de los atributos  
data[["edad"]] = data[["edad"]].astype("int")
data[["imc"]] = data[["imc"]].astype("float")
data[["hijos"]] = data[["hijos"]].astype("int")
data[["costo"]] = data[["costo"]].astype("float")

#Estandarización de los tipo de datos
La fórmula para la conversión es: L/100km = 235 / mpg

In [ ]:
#Ejemplo
#data[''] = 235/data[""]

## Normalizar la colunmas

In [ ]:
# NOrmalizamos los atributos para que queden entre 0 y 1
data['edad'] = data['edad']/data['edad'].max()
data['imc'] = data['imc']/data['imc'].max()
data['costo'] = data['costo']/data['costo'].max()

##Discretizar valores
### Sin aplicar

In [ ]:
#data.head(5)
#data.tail(5)

##Variable indicadora (o variable ficticia)

In [ ]:
dummy_variable_1 = pd.get_dummies(data["sexo"])
#dummy_variable_1.head(50)

In [ ]:
dummy_variable_1.rename(columns={'femenino':'genero-femenino', 'masculino':'genero-masculino'}, inplace=True)
#dummy_variable_1.head()

In [ ]:
data.describe()

edad          imc        hijos        costo
count  1338.000000  1338.000000  1338.000000  1338.000000
mean      0.612610     0.577139     1.094918     0.208097
std       0.219531     0.114779     1.205493     0.189900
min       0.281250     0.300395     0.000000     0.017592
25%       0.421875     0.494942     0.000000     0.074334
50%       0.609375     0.572181     1.000000     0.147122
75%       0.796875     0.652997     2.000000     0.260935
max       1.000000     1.000000     5.000000     1.000000

In [ ]:
#from google.colab import files
#data.to_excel("dataset_fumadores.xlsx")
#files.download("dataset_fumadores.xlsx")

In [ ]:
data.duplicated().sum()
     

1

In [ ]:
#data.hijos.value_counts()

In [ ]:
#data.hijos.value_counts("normalize = True")
     

In [ ]:
#data.hijos.value_counts().plot(kind="bar")
#plt.title("Cantidad de Hijos ")
#plt.xlabel("Hijos")
#plt.xticks(rotation=0)
#plt.ylabel("Total Hijos")
#plt.show()

##One_hot_encodign

In [ ]:

print(data.info)

<bound method DataFrame.info of           edad       sexo       imc  hijos fumador    region     costo
0     0.296875   femenino  0.525127      0      si  suroeste  0.264777
1     0.281250  masculino  0.635611      1      no   sureste  0.027059
2     0.437500  masculino  0.621118      3      no   sureste  0.069773
3     0.515625  masculino  0.427348      0      no  noroeste  0.344744
4     0.500000  masculino  0.543572      0      no  noroeste  0.060637
...        ...        ...       ...    ...     ...       ...       ...
1333  0.781250  masculino  0.582910      3      no  noroeste  0.166230
1334  0.281250   femenino  0.600791      0      no   noreste  0.034593
1335  0.281250   femenino  0.693582      0      no   sureste  0.025558
1336  0.328125   femenino  0.485601      0      no  suroeste  0.031487
1337  0.953125   femenino  0.547149      0      si  noroeste  0.456973

[1338 rows x 7 columns]>


In [ ]:
# importing one hot encoder 
from sklearn.preprocessing import OneHotEncoder

# Creamos el objeto
onehotencoder = OneHotEncoder()

#reshape the 1-D country array to 2-D as fit_transform expects 2-D and finally fit the object 



In [ ]:
S = onehotencoder.fit_transform(data.sexo.values.reshape(-1,1)).toarray()
S


array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [ ]:
dfOneHotS = pd.DataFrame(S, columns = ["sexo"+str(int(i)) for i in range(S.shape[1])]) 

In [ ]:
df = pd.concat([data, dfOneHotS], axis=1)
#df

In [ ]:
F = onehotencoder.fit_transform(data.fumador.values.reshape(-1,1)).toarray()
F

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [ ]:
dfOneHotF = pd.DataFrame(F, columns = ["fumador"+str(int(i)) for i in range(S.shape[1])]) 

In [ ]:
data = pd.concat([data,dfOneHotS, dfOneHotF,], axis=1)
#data

In [ ]:
data= data.drop(['sexo','fumador'], axis=1) 
data.head(5)

edad       imc  hijos    region     costo  sexo0  sexo1  fumador0  \
0  0.296875  0.525127      0  suroeste  0.264777    1.0    0.0       0.0   
1  0.281250  0.635611      1   sureste  0.027059    0.0    1.0       1.0   
2  0.437500  0.621118      3   sureste  0.069773    0.0    1.0       1.0   
3  0.515625  0.427348      0  noroeste  0.344744    0.0    1.0       1.0   
4  0.500000  0.543572      0  noroeste  0.060637    0.0    1.0       1.0   

   fumador1  
0       1.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0

In [ ]:
data = data.dropna()

In [ ]:
data.head(5)

edad       imc  hijos    region     costo  sexo0  sexo1  fumador0  \
0  0.296875  0.525127      0  suroeste  0.264777    1.0    0.0       0.0   
1  0.281250  0.635611      1   sureste  0.027059    0.0    1.0       1.0   
2  0.437500  0.621118      3   sureste  0.069773    0.0    1.0       1.0   
3  0.515625  0.427348      0  noroeste  0.344744    0.0    1.0       1.0   
4  0.500000  0.543572      0  noroeste  0.060637    0.0    1.0       1.0   

   fumador1  
0       1.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0

In [ ]:
Re = onehotencoder.fit_transform(data.region.values.reshape(-1,1)).toarray()
Re

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [ ]:
dfOneHotRe = pd.DataFrame(Re, columns = ["region"+str(int(i)) for i in range(X.shape[1])])

In [ ]:
data = pd.concat([data,dfOneHotRe], axis=1)

In [ ]:
data= data.drop(['region'], axis=1) 

In [ ]:
data.head(5)

edad       imc  hijos     costo  sexo0  sexo1  fumador0  fumador1  \
0  0.296875  0.525127      0  0.264777    1.0    0.0       0.0       1.0   
1  0.281250  0.635611      1  0.027059    0.0    1.0       1.0       0.0   
2  0.437500  0.621118      3  0.069773    0.0    1.0       1.0       0.0   
3  0.515625  0.427348      0  0.344744    0.0    1.0       1.0       0.0   
4  0.500000  0.543572      0  0.060637    0.0    1.0       1.0       0.0   

   region0  region1  region2  region3  
0      0.0      0.0      0.0      1.0  
1      0.0      0.0      1.0      0.0  
2      0.0      0.0      1.0      0.0  
3      0.0      1.0      0.0      0.0  
4      0.0      1.0      0.0      0.0

In [ ]:
# Calculamos Variance Inflation Factor(VIF).
# Cuantifica la  multicolinealidad en un análisis de regresión normal de mínimos cuadrados.
# VIF=1, Baja Multicollinearidad
# VIF=1 VIF<5, Moderada Multicollinearidad
# VIF=1 VIF>5, Multicollinearity Extrema (Se busca evitar)

import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [ ]:
# Seleccionamos las variables que vamos a analizar 
X = data[['costo','fumador0', 'fumador1']]
  
# VIF dataframe
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
  
# calculating VIF for each feature

vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]
print(vif_data)

    feature       VIF
0     costo  2.629951
1  fumador0  2.015228
2  fumador1  4.775201


In [ ]:
X = data[['edad','fumador0', 'fumador1']]
  
# VIF dataframe
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
  
# calculating VIF for each feature

vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]
print(vif_data)

    feature       VIF
0      edad  1.000626
1  fumador0  7.257504
2  fumador1  2.540961
